name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install

      - name: Run black
        run: black --check .

      - name: Run commit-linter
        run: commit-linter --from=${{ github.event.pull_request.base.sha }} --to=${{ github.event.pull_request.head.sha }}
